sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t kalin/frontend-course -f Dockerfile.dev .

script:
  - docker run -e CI=true kalin/frontend-course npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'frontend-course'
  env: 'FrontendCourse-env'
  bucket_name: 'elasticbeanstalk-us-east-2-221771364686'
  bucket_path: 'frontend-course'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
